service: aws-node-simple-http-endpoint
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  currentTime:
    handler: /src/handler.getCurrTime
    events:
      - httpApi:
          path: /time
          method: get
  greetingLoc:
    handler: /src/handler.getLocGreeting
    events:
      - httpApi:
          path: /greeting
          method: get
